package com.wzy.lamanpro.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wzy.lamanpro.bean.HisData;
import com.wzy.lamanpro.bean.Users;
import com.wzy.lamanpro.bean.ProductData;
import com.wzy.lamanpro.bean.Calibration;
import com.wzy.lamanpro.bean.ReportData;

import com.wzy.lamanpro.bean.HisDataDao;
import com.wzy.lamanpro.bean.UsersDao;
import com.wzy.lamanpro.bean.ProductDataDao;
import com.wzy.lamanpro.bean.CalibrationDao;
import com.wzy.lamanpro.bean.ReportDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hisDataDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig productDataDaoConfig;
    private final DaoConfig calibrationDaoConfig;
    private final DaoConfig reportDataDaoConfig;

    private final HisDataDao hisDataDao;
    private final UsersDao usersDao;
    private final ProductDataDao productDataDao;
    private final CalibrationDao calibrationDao;
    private final ReportDataDao reportDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hisDataDaoConfig = daoConfigMap.get(HisDataDao.class).clone();
        hisDataDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        productDataDaoConfig = daoConfigMap.get(ProductDataDao.class).clone();
        productDataDaoConfig.initIdentityScope(type);

        calibrationDaoConfig = daoConfigMap.get(CalibrationDao.class).clone();
        calibrationDaoConfig.initIdentityScope(type);

        reportDataDaoConfig = daoConfigMap.get(ReportDataDao.class).clone();
        reportDataDaoConfig.initIdentityScope(type);

        hisDataDao = new HisDataDao(hisDataDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        productDataDao = new ProductDataDao(productDataDaoConfig, this);
        calibrationDao = new CalibrationDao(calibrationDaoConfig, this);
        reportDataDao = new ReportDataDao(reportDataDaoConfig, this);

        registerDao(HisData.class, hisDataDao);
        registerDao(Users.class, usersDao);
        registerDao(ProductData.class, productDataDao);
        registerDao(Calibration.class, calibrationDao);
        registerDao(ReportData.class, reportDataDao);
    }
    
    public void clear() {
        hisDataDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
        productDataDaoConfig.clearIdentityScope();
        calibrationDaoConfig.clearIdentityScope();
        reportDataDaoConfig.clearIdentityScope();
    }

    public HisDataDao getHisDataDao() {
        return hisDataDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public ProductDataDao getProductDataDao() {
        return productDataDao;
    }

    public CalibrationDao getCalibrationDao() {
        return calibrationDao;
    }

    public ReportDataDao getReportDataDao() {
        return reportDataDao;
    }

}
