package com.wzy.lamanpro.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REPORT_DATA".
*/
public class ReportDataDao extends AbstractDao<ReportData, Long> {

    public static final String TABLENAME = "REPORT_DATA";

    /**
     * Properties of entity ReportData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileName = new Property(1, String.class, "fileName", false, "FILE_NAME");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property TestAccount = new Property(3, String.class, "testAccount", false, "TEST_ACCOUNT");
        public final static Property TestName = new Property(4, String.class, "testName", false, "TEST_NAME");
        public final static Property TestLocal = new Property(5, String.class, "testLocal", false, "TEST_LOCAL");
    }


    public ReportDataDao(DaoConfig config) {
        super(config);
    }
    
    public ReportDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REPORT_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILE_NAME\" TEXT," + // 1: fileName
                "\"TIME\" TEXT," + // 2: time
                "\"TEST_ACCOUNT\" TEXT," + // 3: testAccount
                "\"TEST_NAME\" TEXT," + // 4: testName
                "\"TEST_LOCAL\" TEXT);"); // 5: testLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REPORT_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReportData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(2, fileName);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String testAccount = entity.getTestAccount();
        if (testAccount != null) {
            stmt.bindString(4, testAccount);
        }
 
        String testName = entity.getTestName();
        if (testName != null) {
            stmt.bindString(5, testName);
        }
 
        String testLocal = entity.getTestLocal();
        if (testLocal != null) {
            stmt.bindString(6, testLocal);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReportData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(2, fileName);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String testAccount = entity.getTestAccount();
        if (testAccount != null) {
            stmt.bindString(4, testAccount);
        }
 
        String testName = entity.getTestName();
        if (testName != null) {
            stmt.bindString(5, testName);
        }
 
        String testLocal = entity.getTestLocal();
        if (testLocal != null) {
            stmt.bindString(6, testLocal);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReportData readEntity(Cursor cursor, int offset) {
        ReportData entity = new ReportData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fileName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // testAccount
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // testName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // testLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReportData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTestAccount(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTestName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTestLocal(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReportData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReportData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReportData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
